-- Vendored from ../../schemas/memory_store_schema.sql on 2026-06-12 for THESIS_RUNTIME_TOOL schema v2 base.
-- Do not edit this file for v3 changes; add additive migrations under pipeline/memory/migrations/.
-- memory_store_schema.sql
-- SQLite schema for AMT long-form translation memory.
-- Use one memory.sqlite3 per job under data/jobs/{job_id}/memory.sqlite3.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS documents (
  doc_id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  source_filename TEXT,
  source_lang TEXT DEFAULT 'en',
  target_lang TEXT DEFAULT 'vi',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  metadata_json TEXT DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS blocks (
  block_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  order_index INTEGER NOT NULL,
  page INTEGER,
  block_type TEXT,
  parent_type TEXT,
  chapter_id TEXT,
  scene_id TEXT,
  text TEXT NOT NULL DEFAULT '',
  original_text TEXT,
  bbox_json TEXT DEFAULT '{}',
  style_json TEXT DEFAULT '{}',
  translation_mode TEXT,
  content_kind TEXT,
  strategy TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_blocks_doc_order ON blocks(doc_id, order_index);
CREATE INDEX IF NOT EXISTS idx_blocks_doc_page ON blocks(doc_id, page);
CREATE INDEX IF NOT EXISTS idx_blocks_scene ON blocks(doc_id, scene_id);

CREATE TABLE IF NOT EXISTS scenes (
  scene_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  chapter_id TEXT,
  block_start TEXT,
  block_end TEXT,
  summary_source TEXT DEFAULT '',
  summary_target TEXT DEFAULT '',
  active_entities_json TEXT DEFAULT '[]',
  active_locations_json TEXT DEFAULT '[]',
  confidence REAL DEFAULT 0.5,
  salience REAL DEFAULT 0.5,
  source_refs_json TEXT DEFAULT '[]',
  status TEXT DEFAULT 'active',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_scenes_doc_chapter ON scenes(doc_id, chapter_id);

CREATE TABLE IF NOT EXISTS entities (
  entity_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  canonical_source TEXT NOT NULL,
  canonical_target TEXT,
  entity_type TEXT DEFAULT 'unknown',
  gender TEXT DEFAULT 'unknown',
  role TEXT DEFAULT '',
  importance REAL DEFAULT 0.5,
  first_block_id TEXT,
  latest_block_id TEXT,
  aliases_source_json TEXT DEFAULT '[]',
  aliases_target_json TEXT DEFAULT '[]',
  source_pronouns_json TEXT DEFAULT '[]',
  preferred_vietnamese_forms_json TEXT DEFAULT '{}',
  social_role TEXT DEFAULT '',
  speaker_style TEXT DEFAULT '',
  relations_json TEXT DEFAULT '[]',
  evidence_span_ids_json TEXT DEFAULT '[]',
  confidence REAL DEFAULT 0.5,
  visibility TEXT DEFAULT 'normal',
  valid_from TEXT,
  valid_to TEXT,
  supersedes_json TEXT DEFAULT '[]',
  conflicts_with_json TEXT DEFAULT '[]',
  status TEXT DEFAULT 'candidate',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_entities_doc ON entities(doc_id);
CREATE INDEX IF NOT EXISTS idx_entities_status ON entities(doc_id, status);
CREATE INDEX IF NOT EXISTS idx_entities_importance ON entities(doc_id, importance DESC);

CREATE TABLE IF NOT EXISTS mentions (
  mention_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  entity_id TEXT,
  block_id TEXT NOT NULL,
  surface TEXT NOT NULL,
  mention_type TEXT DEFAULT 'unknown',
  char_start INTEGER,
  char_end INTEGER,
  confidence REAL DEFAULT 0.5,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
  FOREIGN KEY(entity_id) REFERENCES entities(entity_id) ON DELETE SET NULL,
  FOREIGN KEY(block_id) REFERENCES blocks(block_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mentions_doc_block ON mentions(doc_id, block_id);
CREATE INDEX IF NOT EXISTS idx_mentions_entity ON mentions(doc_id, entity_id);
CREATE INDEX IF NOT EXISTS idx_mentions_surface ON mentions(doc_id, surface);

CREATE TABLE IF NOT EXISTS events (
  event_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  chapter_id TEXT,
  scene_id TEXT,
  timeline_order INTEGER,
  summary_source TEXT NOT NULL,
  summary_target TEXT DEFAULT '',
  participants_json TEXT DEFAULT '[]',
  location_entity_id TEXT,
  consequences TEXT DEFAULT '',
  source_refs_json TEXT DEFAULT '[]',
  confidence REAL DEFAULT 0.5,
  salience REAL DEFAULT 0.5,
  status TEXT DEFAULT 'candidate',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
  FOREIGN KEY(scene_id) REFERENCES scenes(scene_id) ON DELETE SET NULL,
  FOREIGN KEY(location_entity_id) REFERENCES entities(entity_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_events_doc_timeline ON events(doc_id, timeline_order);
CREATE INDEX IF NOT EXISTS idx_events_doc_scene ON events(doc_id, scene_id);

CREATE TABLE IF NOT EXISTS speaker_turns (
  speaker_turn_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  block_id TEXT NOT NULL,
  scene_id TEXT,
  turn_index INTEGER,
  quote_text TEXT DEFAULT '',
  speaker_entity_id TEXT,
  addressee_entity_id TEXT,
  dialogue_position TEXT DEFAULT '',
  speech_verb TEXT DEFAULT '',
  evidence_text TEXT DEFAULT '',
  confidence REAL DEFAULT 0.5,
  status TEXT DEFAULT 'candidate',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
  FOREIGN KEY(block_id) REFERENCES blocks(block_id) ON DELETE CASCADE,
  FOREIGN KEY(scene_id) REFERENCES scenes(scene_id) ON DELETE SET NULL,
  FOREIGN KEY(speaker_entity_id) REFERENCES entities(entity_id) ON DELETE SET NULL,
  FOREIGN KEY(addressee_entity_id) REFERENCES entities(entity_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_speaker_turns_doc_block ON speaker_turns(doc_id, block_id);
CREATE INDEX IF NOT EXISTS idx_speaker_turns_doc_scene_turn ON speaker_turns(doc_id, scene_id, turn_index);
CREATE INDEX IF NOT EXISTS idx_speaker_turns_doc_speaker ON speaker_turns(doc_id, speaker_entity_id);


CREATE TABLE IF NOT EXISTS glossary_entries (
  glossary_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  source_term TEXT NOT NULL,
  target_term TEXT NOT NULL,
  term_type TEXT DEFAULT 'term',
  scope TEXT DEFAULT 'global',
  chapter_id TEXT,
  scene_id TEXT,
  do_not_translate INTEGER DEFAULT 0,
  case_sensitive INTEGER DEFAULT 0,
  allowed_variants_json TEXT DEFAULT '[]',
  forbidden_variants_json TEXT DEFAULT '[]',
  examples_json TEXT DEFAULT '[]',
  evidence_span_ids_json TEXT DEFAULT '[]',
  confidence REAL DEFAULT 0.5,
  status TEXT DEFAULT 'candidate',
  occurrences_count INTEGER DEFAULT 0,
  last_block_id TEXT,
  supersedes_json TEXT DEFAULT '[]',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_glossary_doc_source ON glossary_entries(doc_id, source_term);
CREATE INDEX IF NOT EXISTS idx_glossary_doc_status ON glossary_entries(doc_id, status);

CREATE TABLE IF NOT EXISTS memory_items (
  memory_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'global',
  chapter_id TEXT,
  scene_id TEXT,
  block_start TEXT,
  block_end TEXT,
  content TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  salience REAL DEFAULT 0.5,
  confidence REAL DEFAULT 0.5,
  visibility TEXT DEFAULT 'normal',
  valid_from TEXT,
  valid_to TEXT,
  status TEXT DEFAULT 'candidate',
  source_refs_json TEXT NOT NULL DEFAULT '[]',
  supersedes_json TEXT DEFAULT '[]',
  conflicts_with_json TEXT DEFAULT '[]',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  version INTEGER DEFAULT 1,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_memory_doc_type ON memory_items(doc_id, memory_type);
CREATE INDEX IF NOT EXISTS idx_memory_doc_scope ON memory_items(doc_id, scope);
CREATE INDEX IF NOT EXISTS idx_memory_status ON memory_items(doc_id, status);
CREATE INDEX IF NOT EXISTS idx_memory_scene ON memory_items(doc_id, scene_id);

CREATE TABLE IF NOT EXISTS translation_records (
  block_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  source_text TEXT NOT NULL,
  target_text TEXT DEFAULT '',
  memory_pack_id TEXT,
  memory_pack_hash TEXT,
  memory_refs_json TEXT DEFAULT '[]',
  coreference_decisions_json TEXT DEFAULT '[]',
  model TEXT,
  provider TEXT,
  quality_json TEXT DEFAULT '{}',
  glossary_hits_json TEXT DEFAULT '[]',
  reviewed INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
  FOREIGN KEY(block_id) REFERENCES blocks(block_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_translation_records_doc ON translation_records(doc_id);
CREATE INDEX IF NOT EXISTS idx_translation_records_pack ON translation_records(doc_id, memory_pack_id);

CREATE TABLE IF NOT EXISTS human_feedback (
  feedback_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  block_id TEXT NOT NULL,
  source_text TEXT NOT NULL,
  before_translation TEXT DEFAULT '',
  after_translation TEXT NOT NULL,
  feedback_type TEXT DEFAULT 'manual_edit',
  derived_memory_ids_json TEXT DEFAULT '[]',
  confidence REAL DEFAULT 1.0,
  status TEXT DEFAULT 'active',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
  FOREIGN KEY(block_id) REFERENCES blocks(block_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_feedback_doc_block ON human_feedback(doc_id, block_id);

CREATE TABLE IF NOT EXISTS memory_packs (
  pack_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  block_id TEXT NOT NULL,
  pack_hash TEXT NOT NULL,
  prompt_version TEXT DEFAULT 'v1',
  estimated_tokens INTEGER DEFAULT 0,
  payload_json TEXT NOT NULL,
  memory_refs_json TEXT DEFAULT '[]',
  retrieval_debug_json TEXT DEFAULT '{}',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE,
  FOREIGN KEY(block_id) REFERENCES blocks(block_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_packs_doc_block ON memory_packs(doc_id, block_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_packs_doc_hash ON memory_packs(doc_id, pack_hash);

CREATE TABLE IF NOT EXISTS memory_jobs (
  memory_job_id TEXT PRIMARY KEY,
  doc_id TEXT NOT NULL,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  priority INTEGER DEFAULT 100,
  block_start TEXT,
  block_end TEXT,
  payload_json TEXT DEFAULT '{}',
  attempts INTEGER DEFAULT 0,
  last_error TEXT DEFAULT '',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(doc_id) REFERENCES documents(doc_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_memory_jobs_doc_status ON memory_jobs(doc_id, status, priority);

CREATE TABLE IF NOT EXISTS memory_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT OR IGNORE INTO memory_meta(key, value) VALUES ('schema_version', '2');
INSERT OR IGNORE INTO memory_meta(key, value) VALUES ('created_by', 'amt-memory-agent');

-- FTS5 indexes.
CREATE VIRTUAL TABLE IF NOT EXISTS blocks_fts USING fts5(
  block_id UNINDEXED,
  doc_id UNINDEXED,
  text,
  tokenize = 'unicode61'
);

CREATE VIRTUAL TABLE IF NOT EXISTS entities_fts USING fts5(
  entity_id UNINDEXED,
  doc_id UNINDEXED,
  canonical_source,
  canonical_target,
  aliases,
  role,
  tokenize = 'unicode61'
);

CREATE VIRTUAL TABLE IF NOT EXISTS glossary_fts USING fts5(
  glossary_id UNINDEXED,
  doc_id UNINDEXED,
  source_term,
  target_term,
  variants,
  tokenize = 'unicode61'
);

CREATE VIRTUAL TABLE IF NOT EXISTS memory_items_fts USING fts5(
  memory_id UNINDEXED,
  doc_id UNINDEXED,
  content,
  payload_text,
  tokenize = 'unicode61'
);
